import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Check, ShieldCheck, Ruler, Sun, HeartHandshake } from "lucide-react";
import { servicesData } from "@/data/services";
import { locationsData } from "@/data/locations";
import { LeadForm } from "@/components/home/LeadForm";
interface PageProps { params:Promise<{slug:string}>; }
export function generateStaticParams() { return servicesData.map(service=>({slug:service.slug})); }
export async function generateMetadata({params}:PageProps):Promise<Metadata> { const {slug}=await params; const service=servicesData.find(s=>s.slug===slug); return {title:`${service?.title||'Service not found'} | Allind Safety`,description:service?.shortDescription,openGraph:{title:`${service?.title||'Service'} | Allind Safety`,description:service?.shortDescription,images:service ? [{url:service.image}] : []}}; }
export default async function ServicePage({params}:PageProps) {
 const {slug}=await params; const service=servicesData.find(s=>s.slug===slug); if(!service)notFound();
 const schema={"@context":"https://schema.org","@type":"Service",name:service.title,description:service.shortDescription,areaServed:"Pune",provider:{"@type":"LocalBusiness",name:"Allind Safety",telephone:"+919797974476",address:{"@type":"PostalAddress",streetAddress:"Sangamwadi",addressLocality:"Pune",addressRegion:"Maharashtra",postalCode:"411001",addressCountry:"IN"}}};
 return <><section className="site-container section-space"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Link href="/#services" className="back-link">All safety solutions</Link><div className="detail-hero"><div><span className="eyebrow">MADE TO FIT. MADE TO PROTECT.</span><h1>{service.title}<span>.</span></h1><p>{service.shortDescription}</p><div className="detail-actions"><a href="#service-quote" className="action action-lime">Get a free quote</a><a href="tel:+919797974476" className="action action-outline">Talk to our team</a></div><span className="detail-note"><ShieldCheck size={18}/> Expert installation in Pune</span></div><img src={service.image} alt={service.title+" installation"} width="960" height="720" fetchPriority="high"/></div><div className="detail-content"><div><span className="eyebrow">WHY THIS WORKS FOR YOUR SPACE</span><h2>Every detail,<br/>thought through.</h2><p>{service.fullDescription}</p><ul className="feature-list">{service.features.map(feature=><li key={feature}><Check size={18}/><span>{feature}</span></li>)}</ul></div><aside className="spec-panel"><h3>The material details.</h3>{[{icon:Ruler,label:"Material",value:service.specs.material},{icon:Sun,label:"Expected lifespan",value:service.specs.durability},{icon:HeartHandshake,label:"Warranty",value:service.specs.warranty},{icon:ShieldCheck,label:"Strength",value:service.specs.strength}].map(({icon:Icon,label,value})=><div key={label}><Icon size={20}/><div><span>{label}</span><strong>{value}</strong></div></div>)}<p>Confirm material specifications and warranty terms with our team before installation.</p></aside></div><div className="detail-areas"><h2>Installed across Pune.</h2><div className="location-chips">{locationsData.map(loc=><Link href={`/locations/${loc.slug}`} key={loc.slug}>{loc.name}</Link>)}</div></div></section><section id="service-quote" className="detail-quote section-space"><div className="site-container"><div className="section-heading"><div><span className="eyebrow">LET’S FIND YOUR FIT</span><h2>A free visit.<br/>A clear quote.</h2></div><p>Share a few details and talk to our team about {service.title.toLowerCase()}.</p></div><div className="detail-quote-form"><LeadForm minimal/></div></div></section></>;
}
