import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Check, MapPin } from "lucide-react";
import { locationsData } from "@/data/locations";
import { servicesData } from "@/data/services";
import { LeadForm } from "@/components/home/LeadForm";
interface PageProps { params:Promise<{slug:string}>; }
export function generateStaticParams(){return locationsData.map(loc=>({slug:loc.slug}));}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const {slug}=await params;const loc=locationsData.find(l=>l.slug===slug);return {title:`Safety Nets in ${loc?.name||'Pune'} | Allind Safety`,description:`Safety nets, pigeon nets, and invisible grills in ${loc?.name||'Pune'}, Pune. Ask our local team for a free site visit and clear quote.`};}
export default async function LocationPage({params}:PageProps){const {slug}=await params;const loc=locationsData.find(l=>l.slug===slug);if(!loc)notFound();const services=servicesData.filter(service=>loc.popularServices.includes(service.slug));const schema={"@context":"https://schema.org","@type":"Service",name:`Safety net installation in ${loc.name}`,areaServed:{"@type":"Place",name:`${loc.name}, Pune`},provider:{"@type":"LocalBusiness",name:"Allind Safety",telephone:"+919797974476",address:{"@type":"PostalAddress",streetAddress:"Sangamwadi",addressLocality:"Pune",addressRegion:"Maharashtra",postalCode:"411001",addressCountry:"IN"}}};return <><section className="site-container section-space"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Link href="/locations" className="back-link">All our service areas</Link><div className="detail-hero"><div><span className="eyebrow"><MapPin size={16}/> {loc.name.toUpperCase()} / PUNE</span><h1>Safer spaces<br/>in {loc.name}<span>.</span></h1><p>{loc.description}</p><a href="#local-quote" className="action action-lime">Book a free site visit</a></div><picture><source type="image/webp" srcSet="/optimized/hero-image-640.webp 640w, /optimized/hero-image-1200.webp 1200w" sizes="(max-width:760px) 100vw, 50vw"/><img src="/optimized/hero-image-1200.webp" alt="Protected apartment balcony with open city views" width="1448" height="1086"/></picture></div><div className="detail-areas"><div className="section-heading"><div><span className="eyebrow">YOUR LOCAL SAFETY SOLUTIONS</span><h2>A better fit for your home.</h2></div></div><div className="service-grid">{services.map(service=><Link href={`/services/${service.slug}`} key={service.slug} className="service-card"><div className="service-photo"><img src={service.image} alt={service.title} width="960" height="720" loading="lazy"/></div><div className="service-info"><h3>{service.title}</h3><p>{service.shortDescription}</p><span className="text-link">Explore this service</span></div></Link>)}</div></div><div className="local-faq"><h2>Your questions, answered.</h2><div className="faq-list">{loc.faq.map(faq=><details key={faq.question}><summary>{faq.question}<span aria-hidden="true">+</span></summary><p>{faq.answer}</p></details>)}</div></div><div className="local-highlights"><span className="eyebrow">WHAT TO EXPECT</span><ul className="feature-list">{loc.highlights.map(text=><li key={text}><Check size={18}/><span>{text}</span></li>)}</ul></div></section><section className="detail-quote section-space" id="local-quote"><div className="site-container"><div className="section-heading"><div><span className="eyebrow">LET’S TALK ABOUT YOUR SPACE</span><h2>Book a visit in {loc.name}.</h2></div></div><div className="detail-quote-form"><LeadForm minimal/></div></div></section></>;}
